### ISSUE TITLE
A verbose explanation of the settings.yaml file and data formats

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/flexynesis#38]
It would be nice to have a webpage which explains how to construct the settings yaml file, and how
the input files should look like? The format and naming?
https://github.com/BIMSBbioinfo/flexynesis-benchmarks/blob/main/settings.yaml

**Comment by borauyar** [comment]
The issue moved to the pipeline repo: https://github.com/BIMSBbioinfo/flexynesis-benchmarks/issues/1
