### ISSUE TITLE
Description of the input folder for the DataImportner

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/flexynesis#42]
I would be extremely beneficial to have a picture of the folder structure for the DataImporter.
A function that would take the data and prepare the folder would also be awesome.

**Comment by borauyar** [comment]
Preparing the input folder depends on some decisions that are up to the user. How to split the dataset in train/test depends on which clinical variables the user is interested in. Also, the user could be interested in training a model on one dataset and testing it on a different dataset. We could maybe provide some function that could take a single dataset and randomly split it into two groups.

**Comment by borauyar** [comment]
Input folder description is on the main README.
